version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules

volumes:
  node_modules:
    driver: local
